spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/appgestionaleaziendale"
    username: "root"
    password: "ippobau17"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    secret: "GbOGC6XP6uhqfNUzDIYeqqwO34Ne1EuMOrtsiatc0wo="